          #include <iostream>
          #include <exception>
          class myexception : public std::exception{
              public:
                  virtual const char* what() const throw(){
                      return "insufficient balance";
                  }
          } myex;


          void getMoney(int request_amount){
              int balance = 10000;
              if(request_amount > balance){
                  throw myex;
              }else{
                  std::cout << "remaining balance : " << balance - request_amount << std::endl;
              }
          }
          int main(){
              std::cout << "enter request amout" << std::endl;
              int req_amout;
              std::cin >> req_amout;
              try{
                  getMoney(req_amout);
              }catch(myexception& m){
                  std::cout << m.what() << std::endl;
              }
              return 0;
          }

          ouptut :

          enter request amout
          50000
          insufficient balance
